[workspace]
members = [
    "bin/collator",
    "runtime/local",
    "runtime/shiden",
    "runtime/shibuya",
    "frame/block-reward",
    "frame/custom-signatures",
    "frame/dapps-staking",
    "precompiles/staking",
]

[profile.release]
# Astar runtime requires unwinding.
panic = "unwind"


[patch.crates-io]
evm = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11"}
evm-runtime = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
evm-gasometer = { git = "https://github.com/purestake/evm", branch = "moonbeam-polkadot-v0.9.11" }
ethereum = { git = "https://github.com/purestake/ethereum", branch = "joshy-scale-info" }
