[package]
name = "plasm-cli"
version = "0.7.0"
authors = [
    "Takumi Yamashita <takumi@stake.co.jp>",
    "Aleksandr Krupenkin <aleksandr@stake.co.jp>",
]
description = "Plasm node implementation in Rust."
build = "build.rs"
edition = "2018"
default-run = "plasm-node"

[[bin]]
name = "plasm-node"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# thidr-party dependencies
codec = { package = "parity-scale-codec", version = "1.0.6" }
serde = { version = "1.0.102", features = [ "derive" ] }
futures01 = { package = "futures", version = "0.1.29" }
futures = { version = "0.3.1", features = ["compat"] }
hex-literal = "0.2.1"
serde_json = "1.0"
log = "0.4.8"
structopt = "0.3.3"
jsonrpc-core = "14.0.3"

# primitives
primitives = { package = "sp-core", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
sp-runtime = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
babe-primitives = { package = "sp-consensus-babe", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
inherents = { package = "sp-inherents", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }

# client dependencies
client = { package = "sc-client", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
client-api = { package = "sc-client-api", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
chain-spec = { package = "sc-chain-spec", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
txpool = { package = "sc-transaction-pool", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
txpool-api = { package = "sp-transaction-pool", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
network = { package = "sc-network", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
babe = { package = "sc-consensus-babe", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
offchain = { package = "sc-offchain", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
client-db = { package = "sc-client-db", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0", default-features = false }
sc-rpc = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
basic-authorship = { package = "sc-basic-authority", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
sc-service = { git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
telemetry = { package = "sc-telemetry", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
consensus-common = { package = "sp-consensus", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }

# plasm-specific dependencies
plasm-primitives = { path = "../primitives" }
plasm-executor = { path = "../executor" }
plasm-runtime = { path = "../runtime" }
plasm-rpc = { path = "../rpc" }

# frame dependencies
system = { package = "frame-system", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
timestamp = { package = "pallet-timestamp", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
contracts = { package = "pallet-contracts", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0", default-features = false }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
finality-tracker = { package = "pallet-finality-tracker", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }

# CLI-specific dependencies
tokio = { version = "0.1.22", optional = true }
exit-future = { version = "0.1.4", optional = true }
sc-cli = { package = "sc-cli", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0", optional = true }
ctrlc = { version = "3.1.3", features = ["termination"], optional = true }

[dev-dependencies]
service-test = { package = "sc-service-test", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }

[build-dependencies]
sc-cli = { package = "sc-cli", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
build-script-utils = { package = "substrate-build-script-utils", git = "https://github.com/staketechnologies/substrate.git", branch = "plasm-v0.7.0" }
structopt = "0.3.3"
vergen = "3.0.4"

[features]
default = ["cli"]
cli = [
    "sc-service/rocksdb",
    "sc-cli",
    "exit-future",
    "ctrlc",
    "tokio",
]
