name: Format check
on: [push, workflow_dispatch]
jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Install & display rust toolchain
        run: rustup show

      - name: Check targets are installed correctly
        run: rustup target list --installed

      - name: Check fmt
        run: cargo fmt -- --check
